<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SoundFlow" Version="1.2.1" />
    <PackageReference Include="SpotifyAPI.Web" Version="7.*" />
    <PackageReference Include="Google.Cloud.TextToSpeech.V1" Version="3.17.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

</Project>
